spring:
  application:
    name: Job App
  datasource:
    url:jdbc: mysql://localhost:3306/JobDB
    username: root
    password: yashamin
  jpa:
    show-sql: true
    hibernate:
      ddl.auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sql: true
